tidyverse/tidyr

- vignettes/tidy-data.Rmd
While reading this vignette at http://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html, I noticed a few typos.
> Corrected typos

- tests/testthat/test-fill.R
> Fix test-fill

- src/matrixToDataFrame.cpp
- tests/testthat/test-matrixToDataFrame.R
- tests/testthat/test-spread.R
Parts of this probably need to be copied/moved to dplyr.
Fixes #134.
> spread() works with complex values

- R/nest.R
> correct typo in nest() doc

- .travis.yml
> Test oldrel in Travis CI

- tests/testthat/test-drop_na.R
@hadley: This fixes compatibility with the dev version of tibble. Can we do a mini-release?
I wonder what's the best strategy for testing against development versions. Is there a way to install all dependencies from GitHub (if available) instead of CRAN?
> Fix wording of error message in test

- tests/testthat/test-drop_na.R
@hadley: Could you please submit a point release, so that we can update tibble? I've asked @jimhester to submit readr, too.
> Don't test error message that is created by tibble

- vignettes/tidy-data.Rmd
Just in case: “I assign the copyright of this contribution to Hadley Wickham”
> duplicated word removed

- R/data.R
Just a small edit.
I'm not sure how to update `roxygen2` to version 5.0.1.9000, in order to run `roxygen2::roxygenise()` without 'reverting' commit acacd6a38...
I guess the RStudio package manager does not offer it because it's a dev version.
> Fix doc for TB dataset variables.

- R/spread.R
- R/utils.R
- tests/testthat/test-spread.R
> Remove rownames from spread() output

- vignettes/tidy-data.Rmd
I think purrr package is preferable to describe about the concept of "tidy" as it is the member of tidyverse.
> Use purrr::map_dfr() instead of plyr::ldply() in tidy-data vignette

- DESCRIPTION
> Correct version number

- R/separate-rows.R
- R/uncount.R
- R/unite.R
- R/unnest.R
- data-raw/smiths.R
- tests/testthat/test-expand.R
- tests/testthat/test-separate.R
- tests/testthat/test-spread.R
- tests/testthat/test-unnest.R
conservative styling with scope = "spaces" and strict = FALSE.
> styling with styler

- R/uncount.R
Changed signle to single in .remove line
> Spelling Error

- README.Rmd
- README.md
* Fixes #422
* Also props typo fixes from master README.Rmd to md
> Add data import cheatsheet to README

- .Rbuildignore
- .github/move.yml
* Configure move-issues bot (https://github.com/dessant/move-issues)
* Add \.github  to Rbuildignore
> Add move-issues bot config 🤖

- tests/testthat/test-expand.R
- tests/testthat/test-gather.R
- tests/testthat/test-id.R
- tests/testthat/test-separate.R
- tests/testthat/test-spread.R
- tests/testthat/test-underscored.R
- tests/testthat/test-unnest.R
This is a PR that cleans a duplicate test (for gather) and adds further tests to spread (with fill) and id, bringing code coverage of files in /R to 100%.
As it is my first pull request into a public repo, I am more than open for comments on how to improve my process of generating a good pull request. Thanks!
> Clean and improve tests of codes in /R -> 100% coverage

- R/gather.R
- R/nest.R
- R/unite.R
- R/utils.R
Part of #512
See r-lib/rlang#675
I checked that it fixes the 3 package failures you mentioned on Slack.
> Use variant of ensym() that supports quosures

- R/gather.R
- R/spread.R
- R/unite.R
- man/gather.Rd
- man/spread.Rd
- man/tidyr-package.Rd
- man/unite.Rd
Use `""` for new variable creation in docs
Fixes #517
> addresses issue #517

- R/replace_na.R
- man/replace_na.Rd
- man/tidyr-package.Rd
It was an enlightening experience submitting this one line documentation change. I had to install the development versions of dplyr and tibble (lots of compiled code) to document and check (didn't work the first time; I had to restart R a couple of times), got [this error](https://github.com/tidyverse/readxl/issues/520) when running `devtools::document()`, and more. Not necessarily bad/wrong, but enlightening to realize how high the barrier is for even very simple changes.
> Specify what replace_na() returns. Closes #500.

- NEWS.md
- src/melt.cpp
- tests/testthat/test-gather.R
> Check for data frame columns in melt_dataframe

- vignettes/pivot.Rmd
Corrected some typos. Also suggested the addition and removal of commas in 2 places.
> Correting some typos

- vignettes/pivot.Rmd
Tiny typo fix to keep things tidy :smiley:
> Typo: "it generalises it" -> "it generalises in"

- R/pivot-long.R
- R/pivot-wide.R
- tests/testthat/test-pivot-long.R
> .name and .value should always be first and second columns

- R/pivot-long.R
- R/pivot-wide.R
- man/pivot_longer.Rd
- man/pivot_wider.Rd
just found some typos in the documentation
> change doc pivot_long and pivot_wide to pivot_longer and pivot_wider

- vignettes/rectangle.Rmd
Noticed whilst reading through. 
Thanks,
Sam
> Fixing typo in rectangle.Rmd

- R/chop.R
- R/pivot-long.R
- R/pivot-wide.R
- R/rectangle.R
> rename `vec_na` to `vec_init`

- R/chop.R
- R/rectangle.R
- R/utils.R
Now that `vec_slice()` no longer accepts `NULL`
> Compatibility with dev vctrs

- NEWS.md
> Typo in NEWS.md

- NEWS.md
- R/seq.R
- tests/testthat/test-full_seq.R
(the %% operator only returns differences in one direction)
closes #657
> patch full_seq to work for differences that are negative (but within tolerance)

- vignettes/pivot.Rmd
> Fix typo in pivot vignette

- tidyr.Rproj
- vignettes/tidy-data.Rmd
Updated using the new functions.
> updated to use pivot_longer and pivot_wider functions

- R/pivot-long.R
- R/pivot-wide.R
- man/pivot_longer.Rd
- man/pivot_wider.Rd
Just a missing letter in two help pages
> Typo in pivot help page

- R/pivot-wide.R
- man/pivot_longer_spec.Rd
- man/pivot_wider.Rd
* Fixes #756.
* Also roxygenizes documentation fix for `pivot_longer_spec()`.
> Add pre-pivot view of `us_rent_income`

- README.Rmd
- README.md
Delete unnecessary period at the of the sentence "Every row is an observation..".
> Delete one unnecessary period

- R/nest.R
I had the old message come up when writing some code and I had to think about where the message was coming from. This clarifies where it is coming from. It might be useful.
> Added additional details in unnest warning message

- R/pivot-wide.R
- man/pivot_wider_spec.Rd
> Include spec argument in documentation for `pivot_wider_spec()`

- R/separate.R
- man/deprecated-se.Rd
- man/separate.Rd
- Fixes #855
- title modification
- param grammar check
- doc consistency, function vs variable notation
- comment consistency and description
> Refresh `separate()` docs

- R/fill.R
- man/expand.Rd
- man/fill.Rd
> Refresh and add examples for tidyr::fill() 

- vignettes/rectangle.Rmd
This commit is so trivial.  Sorry if it's not even worth the time to read the PR.
> consistent capitalization of GitHub

- DESCRIPTION
- R/expand.R
- man/complete.Rd
- man/deprecated-se.Rd
- man/expand.Rd
> Refresh expand docs

- R/pivot-long.R
- R/pivot-wide.R
- man/pivot_longer.Rd
- man/pivot_longer_spec.Rd
- man/pivot_wider_spec.Rd
- vignettes/pivot.Rmd
> Add examples to function docs and explanation to vignette text for pivot_*_spec functions

- NEWS.md
- R/pivot-wide.R
- man/pivot_wider.Rd
- man/pivot_wider_spec.Rd
- tests/testthat/test-pivot-wide.R
- vignettes/pivot.Rmd
Also includes some documentation for names_sep and names_prefix.
Fixes #899. Fixes #931.
@atusy what do you think? Have I missed anything obvious?
> Add names_glue argument to pivot_wider()

- tests/testthat/test-rectangle.R
> Add unit test for hoisting scalars

- NEWS.md
- R/rectangle.R
- tests/testthat/test-rectangle.R
> Embrace cols everywhere in unnest_auto()

- NEWS.md
- R/pivot-long.R
- tests/testthat/test-pivot-long.R
> pivot_longer(names_to = NULL) to suppress names columns

- vignettes/tidy-data.Rmd
Fixed issue #968 
The definiton of tidy data in [vignettes/tidy-data.Rmd](https://github.com/tidyverse/tidyr/blob/master/vignettes/tidy-data.Rmd) has been updated according to [tidyr website index](https://tidyr.tidyverse.org/index.html), [the Github README](https://github.com/tidyverse/tidyr/blob/master/README.md),  where tidy data is defined as:
1. Every column is variable.
2. Every row is an observation.
3. Every cell is a single value.
> updated definition of tidy data

- NEWS.md
- R/separate.R
- tests/testthat/test-separate.R
> str_split_n() works for factors

- R/data.R
- man/billboard.Rd
Live site shows hanging comma and uncapitalized noun
https://tidyr.tidyverse.org/reference/billboard.html
> Capitalize Billboard as proper noun

- DESCRIPTION
- NEWS.md
- R/pivot-wide.R
- tests/testthat/test-pivot-wide.R
> Pivot wider data table

- R/rectangle.R
> Some easy performance improvements for `hoist()`

- .github/workflows/R-CMD-check.yaml
- .github/workflows/check-devel.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/test-coverage.yaml
- DESCRIPTION
- Updates the standard GitHub actions files
- Updates the devel dplyr GitHub actions file
I am hoping that updating the devel dplyr check file will fix errors like:
https://github.com/tidyverse/tidyr/pull/1141/checks?check_run_id=3263072379
> Update GitHub actions

- README.Rmd
- README.md
tidyr is now a separate cheat sheet, this updates the link and the thumbnail image.
> update cheat sheet links

- R/pivot-long.R
- tests/testthat/test-pivot-long.R
> Can pivot_longer() zero row data frames again.

- R/nest.R
- R/pack.R
- man/nest.Rd
- man/pack.Rd
> Fix reversed documentation of `names_sep` in `pack()` and `nest()`

- NEWS.md
- R/nest.R
- R/pack.R
- tests/testthat/test-pack.R
> Skip non-df-cols in `unpack()` to match `unchop()` and `unpack()`

- R/nest.R
This PR makes `nest()` utilize `pack()` and `chop()` directly, like how `unnest()` uses `unpack()` and `unchop()`.
- We don't want `nest()` to return list-of cols, so we turn them back into list cols before returning
- `pack()` and `chop()` handle `reconstruct_tibble()` so we don't need that here
- The grouped-df method is now simpler, because that exact reconstruction is handled in `pack()` and `chop()`'s calls to `reconstruct_tibble()`
No changes to worse in revdeps
> Utilize `pack()` and `chop()` directly in `nest()`

- R/rectangle.R
- tests/testthat/_snaps/rectangle.md
- tests/testthat/test-rectangle.R
> Check that the input to the rectangling functions is a data frame

- NEWS.md
- R/pivot-long.R
- tests/testthat/test-pivot-long.R
> Transform before casting in `pivot_longer()`

- R/pivot-wide.R
- tests/testthat/_snaps/pivot-wide.md
- tests/testthat/test-pivot-wide.R
> Mention the affected column in the duplicate key warning

- R/pack.R
Now we always use the vctrs utilities for unpacking in tidyr
> Remove final usage of `flatten_at()` by using `df_list()`

- tests/testthat/_snaps/chop.md
- tests/testthat/_snaps/nest.md
- tests/testthat/_snaps/rectangle.md
- tests/testthat/test-chop.R
- tests/testthat/test-nest.R
- tests/testthat/test-rectangle.R
For easier detection of dev rlang changes.
Followup to #1244
> Replace `expect_snapshot(error = TRUE)` with `expect_snapshot(expect_error())`

- NEWS.md
- R/pivot-wide.R
- tests/testthat/test-pivot-wide.R
> Utilize `seq2()` and `vec_chop()` when creating the rectangular frame

- DESCRIPTION
- NEWS.md
- man/tidyr-package.Rd
> Add @mgirlich to authors

- NEWS.md
- R/complete.R
- tests/testthat/test-complete.R
> Ensure `complete()` always applies `fill`

- NEWS.md
- R/complete.R
- man/complete.Rd
- tests/testthat/test-complete.R
> Implement `explicit` argument for `complete()`

- NEWS.md
- R/expand.R
- tests/testthat/test-expand.R
> Revise `fct_unique()` implementation to retain `NA` data

- R/separate.R
- man/separate.Rd
> Update `separate()` example to something the default doesn't handle

- R/extract.R
- R/separate.R
- man/deprecated-se.Rd
- man/extract.Rd
- tests/testthat/_snaps/extract.md
- tests/testthat/_snaps/separate.md
- tests/testthat/test-extract.R
- tests/testthat/test-separate.R
> Update `extract()` documentation and disallow stringr patterns

- NEWS.md
- R/chop.R
- R/rectangle.R
- R/utils.R
- man/hoist.Rd
- tests/testthat/_snaps/rectangle.md
- tests/testthat/test-rectangle.R
> Update `ptype` and `transform` in rectangling functions

- NEWS.md
- R/pivot-long.R
- man/pivot_longer.Rd
- man/pivot_longer_spec.Rd
- tests/testthat/_snaps/pivot-long.md
- tests/testthat/test-pivot-long.R
> Update `pivot_longer()` args taking single/multiple values

- R/chop.R
- R/extract.R
- R/pack.R
- R/rectangle.R
- R/separate.R
- R/utils.R
- tests/testthat/_snaps/chop.md
Fixes error calls and uses r-lib-wide error message.
> Use `rlang::check_required()` instead of `check_present()`

- DESCRIPTION
- NEWS.md
- R/chop.R
- R/drop-na.R
- R/extract.R
- R/fill.R
- R/gather.R
- R/pivot-long.R
- R/pivot-wide.R
- R/rectangle.R
- R/replace_na.R
- R/separate-rows.R
- R/separate.R
- R/unite.R
- R/utils.R
> Remove ellipsis in favor of equivalent rlang functions

- R/pivot-wide.R
As this is generally preferred (see https://github.com/r-lib/vctrs/issues/1409).
> Use `vec_assign()` instead of `vec_slice<-()`

- NEWS.md
- R/pivot-long.R
- man/pivot_longer.Rd
- man/pivot_longer_spec.Rd
- revdep/README.md
- revdep/cran.md
- revdep/failures.md
- revdep/problems.md
- tests/testthat/_snaps/pivot-long.md
- tests/testthat/test-pivot-long.R
- vignettes/pivot.Rmd
Closes #1312 
After looking at this a bit more, I've determined that this argument is mostly useful when you are pivoting every column in your dataset (both the `anscombe` dataset and my original example in #1312 do this). This is somewhat rare, so I'm happy that `cols_vary = "fastest"` was implicitly the default to begin with. That feels like the right choice VS what `gather()` does.
``` r
library(tidyr)
df <- tibble(
start = as.Date(c("2019-01-01", "2019-01-02")),
end = as.Date(c("2019-01-03", "2019-01-04"))
)
df
#> # A tibble: 2 × 2
#>   start      end       
#>   <date>     <date>    
#> 1 2019-01-01 2019-01-03
#> 2 2019-01-02 2019-01-04
pivot_longer(df, c(start, end))
#> # A tibble: 4 × 2
#>   name  value     
#>   <chr> <date>    
#> 1 start 2019-01-01
#> 2 end   2019-01-03
#> 3 …
```
> Implement `cols_vary` argument for `pivot_longer()`

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- R/chop.R
- R/complete.R
- R/nest-legacy.R
- R/pivot-long.R
- R/replace_na.R
- R/tidyr.R
- R/unnest-helper.R
- R/unnest-longer.R
- R/utils.R
- R/zzz.R
- tests/testthat/_snaps/drop-na.md
- tests/testthat/_snaps/hoist.md
- tests/testthat/_snaps/pivot-long.md
- tests/testthat/_snaps/pivot-wide.md
- tests/testthat/_snaps/unnest-wider.md
- tests/testthat/_snaps/unnest.md
- tests/testthat/test-unnest-wider.R
And update lifecycle for released version
> Use latest/dev versions of major dependencies

- NEWS.md
- R/chop.R
- R/drop-na.R
- R/fill.R
- R/pivot-long.R
- R/pivot-wide.R
- R/separate-rows.R
- R/unite.R
- R/unnest-longer.R
- R/unnest-wider.R
- tests/testthat/_snaps/pivot-long.md
- tests/testthat/_snaps/pivot-wide.md
- tests/testthat/test-pivot-long.R
- tests/testthat/test-pivot-wide.R
> Use allow_rename = FALSE

- R/chop.R
- R/complete.R
- R/expand.R
- R/fill.R
- R/pack.R
- R/separate.R
- R/unnest-longer.R
- R/unnest-wider.R
- R/unnest.R
- man/chop.Rd
- man/complete.Rd
- man/expand.Rd
- man/fill.Rd
- man/pack.Rd
- man/separate.Rd
- man/unnest.Rd
- man/unnest_longer.Rd
- man/unnest_wider.Rd
If we're going to use this as the poster child of example sectioning in R Packages, let's make it pretty :nail_care:
> Use the same sectioning approach everywhere

- R/nest.R
- R/tidyr.R
- R/unnest.R
- tests/testthat/_snaps/gather.md
- tests/testthat/_snaps/nest.md
- tests/testthat/_snaps/unnest.md
> Use `local_use_cli()`

- vignettes/rectangle.Rmd
> Add comment about fromJSON

- R/append.R
- R/extract.R
- R/hoist.R
- R/separate.R
- R/spread.R
- R/unite.R
- revdep/README.md
- revdep/cran.md
- revdep/failures.md
- revdep/problems.md
- tests/testthat/_snaps/append.md
- tests/testthat/test-append.R
- tests/testthat/test-hoist.R
Closes #1444 
Closes #1316
`"be829164-2ec7-49e6-a2b8-79c64ea128b4"`
> Rewrite `df_append()` from first principles

- NEWS.md
- R/nest.R
- tests/testthat/_snaps/nest.md
> Use standard lifecycle machinery for `nest()` warning

- DESCRIPTION
- R/separate-wider.R
- tests/testthat/_snaps/append.md
- tests/testthat/_snaps/hoist.md
- tests/testthat/_snaps/pivot-long.md
- tests/testthat/_snaps/separate-wider.md
- tests/testthat/_snaps/unnest-helper.md
> Fix testthat snapshots and update rlang version

- R/data.R
- man/world_bank_pop.Rd
We recommend the World Bank be capitalized.
Signed, Arni Magnusson
> Capitalize the World Bank

- _pkgdown.yml
> Update links to posit

- vignettes/classroom.csv
- vignettes/classroom2.csv
Gone since https://github.com/tidyverse/tidyr/pull/1413/
> Remove two now unused CSVs (they are inlined now)
