tidyverse/tidyr

R/gather.R, tests/testthat/test-gather.R, tests/testthat/test-spread.R
Gathering a `tbl_dt` should produce a `tbl_dt`. Add `gather_.tbl_dt` and
tests. (Also add tests for `spread`.)
=> respect input class

R/gather.R, man/gather.Rd
new example with a standard dataset
shows gather() with and without the dplyr/pipe syntax
gather() called with explicit arg = value pairs
=> add an iris example for gather(), base R and dplyr

R/unite.R, man/unite.Rd
`unite()` documentation description currently states: "Convenience function to paste together multiple functions into one."  I replaced "functions" with "columns", which I think was what was intended.
=> Fix confusing wording in unite() description

R/unnest.R, tests/testthat/test-unnest.R
`nested` should be split as a list, not a data.frame. Otherwise `split.data.frame()` throws a warning when the number of rows in `nested` is not a multiple of the length of `types`.
Example:
```
unnest(data_frame(x = 1:3, y = list(1,2:3,4), z = list(5,6:7,8)))
In split.default(x = seq_len(nrow(x)), f = f, drop = drop, ...) :
data length is not a multiple of split variable
```
=> Avoid warning thrown by split.data.frame()

NEWS.md, R/spread.R, README.md, man/separate.Rd, man/separate_.Rd, man/spread.Rd, man/spread_.Rd, tests/testthat/test-spread.R
Restores `spread()`s ability to create mixed variable types and behaves well when spreading dates and factors. Are there more exotic things I should be worried about?
=> do type conversion after reshaping in spread(); fixes #118

R/unite.R, tests/testthat/test-unite.R
First remove old columns, then add new. With test.
Fixes #89. CC @theunis
=> Change order in unite

NEWS.md, R/separate.R, R/spread.R, man/separate.Rd, man/separate_.Rd
- Warn when using defunct ... argument to separate()
- Declare methods for "grouped_df" class
=> Cleanup for separate() and spread()

src/simplifyPieces.cpp, tests/testthat/test-separate.R
Fixes #170, regarding order of separate columns when fill = "left".
Added test case for this situation
=> Fixes #170, regarding order of separate columns when fill = "left".

R/gather.R
Hi.
It should improve performance when a data.frame no contains NAs.
=> Improve gather_.data.frame when na.rm = TRUE but df really haven't NAs

vignettes/tidy-data.Rmd
The internal link to #multiple-types had square and round braces reversed leading to broken format...
=> Fix link format in vignette

tests/testthat/test-unnest.R
`unnest.grouped_df()` method already implemented.
Do we need a `rowwise_df` method? There seem to be no other methods for `rowwise_df`.
=> Add explicit tests for grouped unnests

DESCRIPTION, NEWS.md, cran-comments.md, man/tidyr-package.Rd, tests/testthat/test-drop_na.R
The next version of tidyselect treats `NULL` as empty inputs, which causes a unit test to fail.
This is also an opportunity to update the NEWS about selection rules backtracking.
=> Hotfix release 0.7.1

src/melt.cpp, tests/testthat/test-gather.R
`STRING_PTR()` is used in the melting code to access elements of a list. This is no longer allowed on R devel: https://github.com/wch/r-source/commit/6ff8e95674c0437d3de4edc04276327f87c64ca8
This should fix it. cc @kevinushey
=> Fix use of STRING_PTR() on R devel

R/nest.R, tests/testthat/test-nest.R
Speed-up is achieved by calling duplicated() over the index vector instead of dplyr::distinct_() over the raw data. Would be even faster with hadley/dplyr#2121.
Test script:
``` r
library(tibble)
devtools::load_all()
data <- expand.grid(a = 1:150, b = 1:150, c = 1:150)
system.time(tidyr::nest(data, b, c))
system.time(tidyr::nest(data, c))
```
Timing current master:
```
> system.time(tidyr::nest(data, b, c))
user  system elapsed 
1.800   0.012   1.814 
> system.time(tidyr::nest(data, c))
user  system elapsed 
4.924   0.008   4.931 
```
Timing this PR:
```
> system.time(tidyr::nest(data, b, c))
user  system elapsed 
1.212   0.004   1.215 
> system.time(tidyr::nest(data, c))
user  system elapsed 
3.968   0.000   3.964 
```
=> Speed up nest()

R/unnest.R, tests/testthat/test-separate.R, tests/testthat/test-unnest.R
Closes #253.
For #308, more work is needed, because this PR loses columns of empty data frames when calling `separate_rows()`.
=> Fix corner case for unnest

R/separate-rows.R, tests/testthat/test-separate.R
=> Leave list columns intact after separate_rows()

NEWS.md, R/separate.R, tests/testthat/test-separate.R
This is a draft PR to Fix #315. All values passed to `stringi::stri_sub` in the `strsep` function are now non-negative as I also noticed a related issue where the use of relatively large negative sep values (relative to the string length) could cause unexpected results.  I'll add a note about this over in the issues section...
=> Fix handling of negative integer values in strsep

R/expand.R, R/extract.R, R/gather.R, R/replace_na.R, R/unnest.R, R/utils.R, tests/testthat/test-fill.R, tests/testthat/test-gather.R, tests/testthat/test-spread.R, tests/testthat/test-unnest.R
First styled with `strict = FALSE` and `scope = "tokens"`. 
Being more invasive than this configuration (e.g. with`strict = TRUE`) did expose one issue with `styler@HEAD`: lines breaks in function calls are not taking into account whether arguments are named or not (https://github.com/tidyverse/style/issues/39). 
I attempted resolve that issue in r-lib/styler#318 and used this version to style with `scope = "tokens"`, `strict = TRUE`. The `enframe_data()` call in `data-raw/smiths.R` was excluded from styling since it needed tribble-like alignment (https://github.com/r-lib/styler/issues/317).
=> styling comprehensively with styler

R/unnest.R, man/unnest.Rd
In the docs for `unnest` I thought 
`@param ... Specification of columns to nest.`
should instead be:
`@param ... Specification of columns to unnest.`
=> Typo in unnest docs

R/uncount.R, man/uncount.Rd
Presumes `opperation` is _not_ an alternate spelling that I can't find. 😉
=> Add missing backtick + fix spelling error

R/separate.R, man/separate.Rd
This is a suggestion to help improve the discoverability of `extract` by adding an @seealso entry to `separate`.  
I thought this might be worth suggesting after responding to a question on the RStudio community site where a user was aware of `separate` but not `extract` (see https://community.rstudio.com/t/getting-parts-of-string-using-regex-and-capturing-parens-in-mutate). This was very similar to my own experience before discovering `extract` existed.
I also thought this might be helpful as `extract` is not currently included on the RStudio `tidyr` cheatsheet while `separate` is.
=> Add mention of `extract` in `separate` docs

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/SUPPORT.md, README.Rmd, README.md
* Add CODE_OF_CONDUCT, CONTRIBUTING, ISSUE_TEMPLATE, and SUPPORT
Uses `usethis::use_tidy_github()`, so same guides as for [dplyr](https://github.com/tidyverse/dplyr/tree/master/.github) etc.
=> Add use_tidy_github() guides

R/spread.R, tests/testthat/test-spread.R
The new format follows the format @hadley laid out in the discussion.
=> More informative error message for duplicate identifiers for rows. Addresses #426.

NEWS.md, R/expand.R, R/spread.R, man/complete.Rd, man/deprecated-se.Rd, man/expand.Rd, tests/testthat/test-expand.R, tests/testthat/test-spread.R
Added a test for type and size of result. `complete` doesn't work though because it relies on `dplyr::left_join` which doesn't support list columns currently, @romainfrancois 🦄
=> part of issue #446, expand supports list columns but complete does not

NEWS.md, R/id.R, tests/testthat/test-id.R, tests/testthat/test-spread.R
shorther repress than on the issue: 
``` r
library(tidyr)
df <- tibble::tibble(
key = factor(c("a", "b", "c"), levels = letters[1:5]),
out = 1:3,
id  = c(a = 1, b = 2, c = 3)
)
spread(df, key, out, drop = FALSE)
#> # A tibble: 3 x 6
#>      id     a     b     c     d     e
#>   <dbl> <int> <int> <int> <int> <int>
#> 1     1     1    NA    NA    NA    NA
#> 2     2    NA     2    NA    NA    NA
#> 3     3    NA    NA     3    NA    NA
```
There are other calls to `attr()` we might want to check:
=> spread() works fine when the id variable has names.

NEWS.md, R/dep-lazyeval.R, R/fill.R, man/deprecated-se.Rd, man/fill.Rd, tests/testthat/test-fill.R
Add option to fill() to both fill-down-then-up and fill-up-then-down. (Issue: https://github.com/tidyverse/tidyr/issues/505)
(Note: This is a replacement for PR #504 which I broke oh-so-hard.)
This is to replace a common idiom of mine, i.e.
```r
df %>%
group_by(group) %>%
tidyr::fill(value, .direction = 'down') %>%
tidyr::fill(value, .direction = 'up') %>%
ungroup()
```
which could become
```r
df %>%
group_by(group) %>%
tidyr::fill(value, .direction = 'downup') %>%
ungroup()
```
Depending upon number of groups and number of variables to replace, the current duplicate call to fill() can be avoided, giving significant speed savings.
I have values only known at some particular time and I need to fill this value both forwards and backwards in time.
I work with clinical trial data, which is …
=> Update to PR #504. Use anonymous function instead of compose

vignettes/pivot.Rmd
I was just reading through the vignette for the new pivot functions and noticed there were a few typos it might be good to fix. The list of things I have changed is below (I find the diff sometimes isn't useful for text where there can be multiple changes on the same line). Some of this might just be my opinion so feel free to ignore anything you don't like.
I also thought the sentence on line 24 wasn't quite clear but I wasn't sure how to fix it, so I left it.
P.S. The new functions look excellent! 👍
Changes:
```
L21: "It's" -> "It"
L55: Add "about"
L55: "there" -> "their
L55: "annaul" -> "annual"
L82: "manully" -> "manually"
L152: Add "and"
L201: "inside" -> "instead"
L234: "even" -> "ever"
L234: "access a" -> "access to a"
L274: "with columns with" -> "with columns"
L294: Removed extra …
```
=> Typos in pivot vignette

vignettes/pivot.Rmd
there was a small typo line 172 (variables)
=> fixing typo in pivot vignette

vignettes/pivot.Rmd
- Fix a few minor typos
- Some copy editing
- Suggest renaming one section: multiple observations per row
- Remove references to `pivot_wide()` and `pivot_long()`
=> Edits to pivot vignette

R/expand.R, man/expand.Rd
I noticed a small typo in the examples of `tidyr` it is the only occurrence of 'measurment' across the whole package. I couldn't update the .Rd file due to `vctrs` install issues on my machine.
=> Correct typo in expand() example

R/nest.R, tests/testthat/test-nest.R
Copy/pasting the current warning throws an unrelated error message, because `unnest()` looks for a column named `name_sep` (instead of recognizing the argument `names_sep`).
=> fix typo in warning message

vignettes/pivot.Rmd
Modified example code blocks based on #666, and descriptions as well.
Beside what is discussed in #666, I reordered column names described in L505, so that the order is consistent to the output data frame.
=> Better example for Wider section of Manual Spec in pivoting vignette

R/pivot-long.R, tests/testthat/test-pivot-long.R
Improve error message when `matches()` is used for `col` argument in `pivot_longer()`, see #665.
=> Improve error message when `matches()` is used for `col` argument in `pivot_longer()`

R/spread.R, man/spread.Rd, man/tidyr-package.Rd
Documentation uses wrong argument names when referring to `pivot_wider()`
=> Typo in spread documentation

vignettes/in-packages.Rmd
`dplyr:select()` -> `dplyr::select()`
=> Fix a typo in in-packages vignette

R/chop.R, R/dep-lazyeval.R, R/gather.R, R/nest-legacy.R, R/nest.R, R/pack.R, R/pivot-long.R, R/pivot-wide.R, R/rectangle.R, R/spread.R, man/chop.Rd, man/deprecated-se.Rd, man/gather.Rd, man/hoist.Rd, man/macros/lifecycle.Rd, man/nest.Rd, man/nest_legacy.Rd, man/pack.Rd, man/pivot_longer.Rd, man/pivot_wider.Rd, man/spread.Rd, man/tidyr-package.Rd
Unfortunately it seems there is no way to use the macro on R 3.2.
=> Fix lifecycle macro on R 3.2

tests/testthat/test-pack.R
This test tests an error that comes from tibble. Is it worth to catch and rethrow an own error here?
=> Fix test warning

NEWS.md, R/rectangle.R, tests/testthat/test-rectangle.R
Fixes #741.
This was a similar problem to a previous issue, where we were assigning to `data[[col]][] <-` when it just needed to be `data[[col]] <- `.
I also changed this for `unnest_longer()`.
Note that there is still another place in `unnest_longer/wider()` where the `data[[col]][] <- ` assignment is used. That one was not adjusted, as it broke tests. I think it makes sense there because at that point `data[[col]]` is often a tibble itself (it was a df-col), and we want to use `data[[col]][] <-` there to perform the assignment, rather than replace the tibble.
``` r
library(tidyr)
df1 <- tibble::tribble(
~type,          ~name, ~var1,
"Country",   "Norway", 169L, 
"Sport",     "Skii", 169L, 
"Country",    "Spain", 150L, 
"Sport",     "Bike", 150L, 
"Sport",   "Soccer", 150L, 
"Sport", …
```
=> Perform direct column replacements in `unnest_longer()` / `unnest_wider()`

R/rectangle.R, man/hoist.Rd
For the examples for hoist, the species for Dory is listed as clownfish. Marlin and Nemo are clownfish while Dory is a blue tang, or a Pacific Regal Blue Tang. I went with the shorter version.
=> Dory is not a clownfish

R/pivot-wide.R, tests/testthat/test-pivot-wide.R
Fixes #804 
I don't think name repair should happen when building the spec. The real application of name repair comes when the spec is used to do the actual pivot.
---
Sidebar: I still think explicit use of `pivot_wider(df, names_from = "...1")` falls under this from [our name repair principles](https://principles.tidyverse.org/names-attribute.html#unique-names):
> When unique-ifying names, we assume that the input names have been repaired by the same strategy, i.e. that we are consuming dogfood. Therefore, pre-existing suffixes of the form `...j` are stripped, prior to (re-)constructing the suffixes. If this interacts poorly with your names, you need to take control of name repair.
It seems pretty artificial (and risky) to hard-code a column name (`"...1"`) that was created through …
=> Don't apply name repair when building spec

NEWS.md, R/expand.R, man/expand.Rd, man/expand_grid.Rd, tests/testthat/test-expand.R
Fixes #798 (Marked as help wanted) 
Notes: 
* Added .name_repair to `nesting` as well as the functions you mentioned in your comment on #798. 
* I wasn't sure how best to include the info about .name_repair in the roxygen so I ended up just copy and pasting it in. 
Very happy to receive any feedback!
Best, 
Jeffrey
=> Add .name_repair to expand functions

NEWS.md, R/chop.R, tests/testthat/test-chop.R
```r
df <- tibble(x = integer(), y = integer())
chop(df, y)
#> # A tibble: 0 x 1
#> # … with 1 variable: x <int>
chop(df, y)
#> # A tibble: 0 x 2
#> # … with 2 variables: x <int>, y <int>
```
=> Preserve width of empty chopped data frames

NEWS.md, R/chop.R, man/chop.Rd, tests/testthat/test-chop.R
Branched from #883 
Helps with roundtrips when the chopped df is emptied. Implementation avoids rbind and is a little faster:
```r
library(vctrs)
library(tidyr)
big <- vec_rbind(!!!rep(list(mtcars), 1000))
bench::mark(chop(big, cyl))[1:8]
#> # A tibble: 1 x 8
#>   expression          min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 chop(big, cyl)     16ms     17ms      58.3     893KB     6.72    26     3
bench::mark(chop(big, cyl))[1:8]
#> # A tibble: 1 x 8
#>   expression          min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 chop(big, cyl)   10.8ms   11.3ms      87.2     893KB     2.03    43     1
```
=> Create list-columns with `list_of()` in `chop()`

vignettes/in-packages.Rmd
The "In packages" vignette needed more work around the switch from travis to gh actions.
=> Finish travis --> gh actions transition

R/separate-rows.R, tests/testthat/test-separate-rows.R
Fixes #1014. Using strsplit caused it to silently drop rows when used against a blank value.
Current version;
``` r
library(tidyr)
df <- tibble(x = 1:3, y = c("a", "d,e,f", ""))
separate_rows(df, y, sep = ",")
#> # A tibble: 4 x 2
#>       x y    
#>   <int> <chr>
#> 1     1 a    
#> 2     2 d    
#> 3     2 e    
#> 4     2 f
```
Which silently drops the last y value.
Updated in this PR and how it was in tidyr 1.1.0
```r
df <- tibble(x = 1:3, y = c("a", "d,e,f", ""))
separate_rows(df, y, sep = ",")
#> # A tibble: 4 x 2
#>       x y    
#>   <int> <chr>
#> 1     1 "a"    
#> 2     2 "d"    
#> 3     2 "e"    
#> 4     2 "f"
#> 5     3 ""
```
=> use str_split_n() to fix #1014

R/pivot-long.R, man/pivot_longer.Rd, man/pivot_longer_spec.Rd
This PR addresses #980, though I'm not sure if it closes it.
It clarifies that `names_ptypes` is used to _confirm_ the type of a variable vs. `names_transform` is used to _change_ it. I think for most situations `names_transform` is what the user wants, not `names_ptypes`, so the paragraph about "if you don't do anything, these are the default types you'll get" is moved under `names_transform`.
=> Clarify names_ptypes vs. names_transform, 

R/pivot-long.R
Changes
* don't create `rows` data frame but slice the vectors directly
* don't use `matrix(byrow = TRUE)` as it is surprisingly slow
It looks like a bug to me that `matrix(x, byrow = TRUE)` is slower than `t(matrix(x))`. Probably, this should be fixed in base R.
```r
library(data.table)
library(tidyr)
data.test <- matrix(
data = sample(
x = c(0L, 1L, 2L, NA_integer_),#the genotypes
size = 2e+07,
replace = TRUE,
prob = c(0.8, 0.10, 0.05, 0.05)
),
nrow = 20000,#number of SNPs/markers
ncol = 1000,#number of samples
dimnames = list(rownames = seq(1, 20000, 1), colnames = seq(1, 1000, 1))
) %>%
tibble::as_tibble(x = ., rownames = "MARKERS")
bench::mark(
pivot = tidyr::pivot_longer(data.test, cols = -MARKERS, names_to = "INDIVIDUALS", values_to = "GENOTYPES"),
melt = …
```
=> speed up `pivot_longer()`

NEWS.md, tests/testthat/test-nest.R
=> Test that the `ptype` argument of `unnest()` works correctly now

NEWS.md, R/pack.R, tests/testthat/test-pack.R
=> Ensure `unpack()` is size stable in the zero col / one row case

R/pack.R
Also removes the TODO about preserving order, which I think is impossible. Consider a data frame with column names `c("x", "y", "z")`. How could `pack(df, c(x, z))` preserve order in any meaningful way?
=> Small revision to `pack()` for clarity

NEWS.md, R/chop.R, tests/testthat/_snaps/chop.md, tests/testthat/test-chop.R
Closes #1205 
Closes #1206 
I think avoiding the `transpose()` call and calling `vec_chop()` directly makes this much easier to reason about
=> Update and simplify `chop()` implementation

NEWS.md, R/nest.R, tests/testthat/test-nest.R
Closes #1134 
Closes #1175 
We don't really need to do the full `eval_select()` call here, we just need to create a nice-ish label for the warning and rework the unnamed dots into a `c(...)` format to pass on to another call to `nest()`.
This should avoid any issues with dbplyr / dtplyr methods.
Also fixed #1175, where a mix of named/unnamed dots could cause some issues.
=> Avoid computing on `.data` in the `nest()` generic

tests/testthat/_snaps/gather.md, tests/testthat/_snaps/nest.md, tests/testthat/_snaps/pivot-wide.md, tests/testthat/_snaps/separate.md, tests/testthat/test-gather.R, tests/testthat/test-nest.R, tests/testthat/test-pivot-wide.R, tests/testthat/test-separate.R
As mentioned in https://github.com/tidyverse/tidyr/pull/1204#discussion_r745873267
=> Update warning related tests to use `expect_snapshot()`

NEWS.md, R/chop.R, tests/testthat/test-chop.R
=> Ensure `ptype` is used on non-list columns in `unchop()`

tests/testthat/_snaps/gather.md, tests/testthat/test-gather.R
Follow up to https://github.com/tidyverse/tidyr/pull/1210
Make sure the snapshot tests don't rely on the current date in any way 🤦
=> Ensure snapshot tests are static

NEWS.md, R/chop.R, R/rectangle.R, R/utils.R, man/hoist.Rd, tests/testthat/_snaps/rectangle.md, tests/testthat/test-rectangle.R
`unnest_longer()`:
Closes #1201
Closes #1199 
Closes #1198 
Closes #1196 
Closes #1195 
Closes #1194 
Closes #1193 
Closes #1034 
Closes #1029 
Closes #740 
`unnest_wider()`:
Closes #1188 
Closes #1187 
Closes #1186
Closes #1125 
Closes #1133 
Closes #1060 
`hoist()`:
Added test of current behavior for #1203 
Closes #1044 
Closes #1000 
Closes #999 
Closes #998 
Closes #996 
Other:
Part of #1185 
---
Affected revdeps:
- ffscrapr
- Pre-emptive PR already merged https://github.com/ffverse/ffscrapr/pull/344
- wehoop
- Lots of off-label usage of `unnest_wider()`. PR https://github.com/saiemgilani/wehoop/pull/14
- Two tests explicitly check for a set of column names after all the unnesting is applied. Fixing the first part of https://github.com/tidyverse/tidyr/issues/1125#issuecomment-959802379 …
=> Rectangling function rewrite

R/extract.R, R/pack.R, R/pivot-long.R, R/pivot-wide.R, R/rectangle.R, R/spread.R, R/utils.R
Closes #1185 
- This ensures a mix of size 0 and size 1 inputs result in a size 0 output
- No `collapse` argument, because that is fundamentally a different operation that should always return a size 1 result
=> Use `vec_paste0()` in place of `paste0()` to avoid recycling issues

NEWS.md, R/replace_na.R, man/replace_na.Rd, tests/testthat/_snaps/replace_na.md, tests/testthat/test-replace_na.R
Revival of https://github.com/tidyverse/tidyr/pull/1109
Closes #1168 
Closes #912 (by mentioning that you should use `across()` in the NEWS bullet)
This PR updates `replace_na()` to utilize vctrs through `vec_equal_na()` and `vec_assign()`. This has two breaking changes:
- `vec_assign()` always casts the RHS to the LHS, but previously with `[<-` the reverse could be true. I think this is a step in the right direction
- This means you can't do `replace = 1.5` on an integer vector
- More practically, it means for lists you can't do `replace = "foo"`, it must be `replace = list("foo")`
- `vec_equal_na()` is now used for detecting missing values. For list-cols, it will only detect `NULL` as missing, while the current implementation will replace `NULL` and empty atomics like `integer()`. …
=> Update `replace_na()` to utilize vctrs

DESCRIPTION, NEWS.md, R/drop-na.R, man/drop_na.Rd, tests/testthat/_snaps/drop-na.md, tests/testthat/test-drop-na.R
Closes #1228 
Closes #1227 
Closes #991 
Closes #906 
Fairly straightforward conversion. Removed `complete_cases()` in favor of `vec_detect_complete()`, which also fixed some edge case bugs.
=> Implement `drop_na()` using `vec_detect_complete()`

NEWS.md, R/rectangle.R, man/hoist.Rd, tests/testthat/_snaps/rectangle.md, tests/testthat/test-rectangle.R
Closes #995 
The best interface we could come up with is to provide a named list of `TRUE` or `FALSE`. This:
- Matches `ptype` and `transform` pretty well
- Isn't ambiguous with a single `TRUE` or `FALSE` in any way
- Is easy to program with internally
=> Implement optional simplification on a per column basis

NEWS.md, R/expand.R, R/pack.R, tests/testthat/_snaps/expand.md, tests/testthat/test-expand.R
Related to auto-naming:
Closes #1221 
Closes #1116 
Closes #1092 
Closes #1037 
Closes #992 
Other:
Closes #1189 
This was a tricky one to fix.
Ultimately, I combined a few ideas together:
- We essentially use `quos_auto_name(repair_auto = "unique", repair_quiet = TRUE)` from https://github.com/r-lib/rlang/pull/1194, but that is in rlang 1.0.0 and we don't use dev rlang yet. So I've just inlined the idea of it for now. Notably, that only performs unique repair on the auto-named inputs, which is definitely the right approach. This avoids getting duplicate names like `<int>` or truncated names like `tibble(...)` when a long tibble expression is inlined.
- We take an approach more similar to `tibble:::tibble_quos()` for iterative expressions (i.e. when the user does `x = 1, y = x`). This …
=> Rework grid functions to be more robust to duplicate auto names

NEWS.md, R/pivot-wide.R, man/pivot_wider.Rd, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R
Closes #1114 
We already allowed a named list of anonymous functions, this fixes the `values_fn = ~mean(.x)` case
=> Allow `values_fn` to be an anonymous function

NEWS.md, R/pivot.R, tests/testthat/_snaps/pivot-long.md, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-long.R, tests/testthat/test-pivot-wide.R
=> Update `wrap_error_names()` to override vctrs name repair `arg`

NEWS.md, R/pivot-wide.R, R/tidyr.R, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R
Closes #1240 
`pivot_longer()` does the same thing with `cols` already, so in some ways this is making `pivot_wider()` more consistent with that.
=> Require at least 1 column selection for `names_from` and `values_from`

NEWS.md, R/pivot-wide.R, R/pivot.R, tests/testthat/_snaps/pivot.md, tests/testthat/test-pivot-wide.R, tests/testthat/test-pivot.R
Closes #1107 
This one is a little tricky to fix, but I think this should work nicely.
It relies on a check that the `.name` column of a spec must be unique. I think this is reasonable, because I can't think of a case where it would be meaningful in either `pivot_wider()` or `pivot_longer()`.
With that restriction in mind, we can preemptively cbind all of the values columns together and reorder them immediately using the original `spec$.name` column. This should contain all of the values column names, and no name repair should have needed to be applied when they were cbind-ed since `.name` is unique.
Only then do we combine the correctly ordered columns with the id columns, and also apply name repair in case any id columns collide with one of the new values columns.
=> Reorder values columns before combining with id columns

NEWS.md, R/pivot-wide.R, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R
=> Throw a useful error when `values_fn` doesn't result in a single value

R/extract.R, tests/testthat/_snaps/append.md, tests/testthat/_snaps/extract.md, tests/testthat/_snaps/full_seq.md, tests/testthat/_snaps/gather.md, tests/testthat/_snaps/nest-legacy.md, tests/testthat/_snaps/pack.md, tests/testthat/_snaps/pivot-long.md, tests/testthat/_snaps/pivot.md, tests/testthat/_snaps/replace_na.md, tests/testthat/_snaps/separate.md, tests/testthat/_snaps/spread.md, tests/testthat/_snaps/uncount.md, tests/testthat/test-append.R, tests/testthat/test-extract.R, tests/testthat/test-full_seq.R, tests/testthat/test-gather.R, tests/testthat/test-nest-legacy.R, tests/testthat/test-pack.R, tests/testthat/test-pivot-long.R, tests/testthat/test-pivot.R, tests/testthat/test-replace_na.R, tests/testthat/test-separate.R, tests/testthat/test-spread.R, tests/testthat/test-uncount.R
This is a preparatory PR for figuring out how much dev rlang is going to touch the error messages
=> Move hard coded `expect_error()` tests to `expect_snapshot(expect_error())`

NEWS.md, R/pivot-wide.R, tests/testthat/test-pivot-wide.R
Closes #1252 
Now that #1253 is merged, we can remove this slightly incorrect conditional code path for the zero column case (because it doesn't handle the zero row case right). But we still need to handle data.table's behavior with `dt[character()]` returning a zero row data table (see https://github.com/tidyverse/tidyr/pull/1073), so we just convert `data` to a tibble early on to avoid this. We do this anyways eventually, so it doesn't affect any behavior.
=> Ensure that pivoting a zero row data frame returns zero rows

NEWS.md, R/pivot-wide.R, man/pivot_wider_spec.Rd, tests/testthat/test-pivot-wide.R
=> Compute `id_cols` by excluding `names_from` and `values_from`

NEWS.md, R/expand.R, tests/testthat/test-complete.R, tests/testthat/test-expand.R
Closes #1258 
Followup to https://github.com/tidyverse/tidyr/pull/1230, extending the same idea to `nesting()`
- This composes better when used inside `complete()` and `expand()`, as recycling is applied more intuitively
- This makes more sense overall, I think, as the "number of combinations" you can get from an empty set should be 1? Like how `prod() == 1L` with `expand_grid()`.
=> Ensure `nesting()` with no inputs returns a 1 row data frame

NEWS.md, R/rectangle.R, tests/testthat/test-rectangle.R
Closes #1259 
This isn't completely perfect, but is an improvement over the current behavior in #1259. It fixes both cases there, but I've added a test to show where it still fails. If you try to use the same plucker twice to extract both duplicated names, then you won't get the expected results since we don't strike after every pluck. This seems like it would be hard to implement correctly, and probably isn't worth it, so I have left that alone.
=> Avoid dropping duplicately named elements in `hoist()`

R/pivot-wide.R, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R
Implements a fix for #1102 even though I closed that already. CC @mgirlich, it turns out I was able to make this a little cleaner. Here is the new warning:
``` r
library(tidyr)
df <- tibble::tribble(
~x, ~y, ~z, ~w,
"a",  2,  4, 6,
"a",  3,  5, 7
)
df
#> # A tibble: 2 × 4
#>   x         y     z     w
#>   <chr> <dbl> <dbl> <dbl>
#> 1 a         2     4     6
#> 2 a         3     5     7
df %>% 
pivot_wider(
names_from = x,
values_from = c(y, z, w),
values_fn = list(y = sum)
)
#> Warning: Values from `w` and `z` are not uniquely identified; output will contain list-cols.
#> * Use `values_fn = list` to suppress this warning.
#> * Use `values_fn = length` to identify where the duplicates arise.
#> * Use `values_fn = {summary_fun}` to summarise duplicates.
#> # A tibble: 1 × 3
#>     y_a z_a …
```
=> Only signal the duplicate warning once, and mention all affected cols

NEWS.md, R/pivot-wide.R, man/pivot_wider.Rd, man/pivot_wider_spec.Rd, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R
Closes #839 
Implements `names_vary`, as described compactly by this comment https://github.com/tidyverse/tidyr/issues/839#issuecomment-993924527
The actual coding of this is fairly straightforward. It just swaps `vec_rep()` for `vec_rep_each()` and vice versa while creating the spec columns.
As shown in https://github.com/tidyverse/tidyr/issues/839#issuecomment-993932843, this can currently be accomplished using `arrange()` on a spec generated by `build_wider_spec()`. But this _feels_ like it might be worth adding an argument for, since it seems to come up fairly often (2 issues and at least 2 stack overflow questions).
=> Implement `names_vary` for `pivot_wider()`

R/chop.R, R/pack.R, man/chop.Rd, man/pack.Rd
Closes #1086 
Upon review:
Changed:
- `chop()` and `pack()` were maturing, but I think they are stable now
Unchanged:
- `spread()` is marked as superseded
- `gather()` is marked as superseded
- `nest_legacy()` and `unnest_legacy()` are marked as superseded
- `nest()` has two deprecated arguments
- Unnamed `...`
- `.key`
- `unnest()` has four deprecated arguments
- `.drop` / `.preserve`
-   `.id`
- `.sep`
- We have deprecated lazy eval versions of the tidyr verbs
I doubt any of this should be changed right now
At first I thought that the lazy eval versions might could be removed, but you have this in the 1.0.0 NEWS:
> All other lazyeval functions have been formally deprecated, and will be made defunct in the next major release.
=> Remove maturing badges for `chop()` and `pack()`

NEWS.md, R/pivot-wide.R, man/pivot_wider.Rd, man/pivot_wider_spec.Rd, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R, vignettes/pivot.Rmd
Closes #770 
Related to #560 
- `names_expand` calls `expand()` on the `names_from` columns while building out the spec. This should be rather cheap, as we don't have to expand the entire data frame.
- `id_expand` calls `complete()` and completes the `id_cols`. The data frame it completes contains the `id_cols` along with the `names_from` and `values_from` columns. I don't think there is any straightforward way to avoid calling `complete()` in favor of just calling `expand()` on the `id_cols`.
- During the `complete()` stage, we fill in the previously implicit missing values in the expanded `values_from` columns
---
Is it worth it? I _think_ so, especially when you look at a few examples and consider the alternatives:
- It is very hard to reach the same efficiency as the approach …
=> Implement `id_expand` and `names_expand` for `pivot_wider()`

NEWS.md, R/pivot-wide.R, man/pivot_wider.Rd, man/pivot_wider_spec.Rd, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R, vignettes/pivot.Rmd
Closes #990 
Closes #1076 (CC @mgirlich I've built off your PR from there and mentioned you in the NEWS)
~_This means we have to tweak https://github.com/tidyverse/tidyr/pull/1277 to also include the columns identified by `unused_fn` when performing the `id_expand` `complete()` step._~ Done in this PR
I was initially a little resistant to this feature, but I've come around and actually think it is pretty neat and solves an otherwise clunky problem. @hadley what do you think? I know we are starting to add quite a few arguments to pivot-wider...
The only _slightly_ weird thing about it is that in order for `unused_fn` to be useful, you have to specify `id_cols` explicitly, otherwise all unspecified cols are treated as `id_cols`! I have mentioned this in the docs.
The original issue uses the …
=> Implement `unused_fn` for summarizing unused columns

R/replace_na.R, tests/testthat/test-replace_na.R
=> Patch `replace_na(NULL)` until vctrs fix is released

NEWS.md, R/dep-lazyeval.R
Closes #1294 
FYI @hadley - We couldn't move the lazyeval variants to the defunct stage, because some of them haven't made it to the soft-deprecated stage yet. In particular, a few people use `gather_()` still because it hasn't been soft-deprecated https://github.com/tidyverse/tidyr/pull/1281#issuecomment-996848881, like plotly https://github.com/plotly/plotly.R/issues/2088
=> Soft-deprecate remaining lazyeval variants of tidyr verbs

R/pivot-long.R, man/pivot_longer.Rd, man/pivot_longer_spec.Rd, tests/testthat/test-pivot-long.R
=> Add backwards compat support for `list()` in `names/values_ptypes`

NEWS.md, R/complete.R, R/expand.R, man/complete.Rd, man/expand.Rd, tests/testthat/test-complete.R, tests/testthat/test-expand.R
Closes #1299
Follow up to #1289 
In #1289 we added a grouped-df method for `complete()` that calls `complete()` "within" each group. This would send the entire group slice of data (including the grouping column) into the inner call to `complete()`. This turns out to be buggy, since it can generate missing values in the grouping columns if the within-group-expansion adds rows:
``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)
df <- tibble(
g = c("x", "x", "y"),
a = c(1, 2, 2),
b = c(1, 2, 2)
)
gdf <- group_by(df, g)
gdf
#> # A tibble: 3 × 3
#> # Groups:   g [2]
#>   g         a     b
#>   <chr> <dbl> <dbl>
#> 1 x         1     1
#> 2 x         2     2
#> 3 y         2     2
complete(gdf, a, b)
#> # A tibble: 5 × 3
#> # Groups:   g [3]
#>   g         a     b
#>   <chr> <dbl> <dbl> …
```
=> Disallow access to group columns in `expand()` and `complete()`

R/nest.R, tests/testthat/_snaps/nest.md, tests/testthat/test-nest.R
Small improvement to the `nest()` generic warning regarding unnamed inputs. If we only have one input, then we don't need to wrap it in `c()`
=> Only use `c()` when there are >1 unnamed inputs

DESCRIPTION, man/extract.Rd, man/gather.Rd, man/nest_legacy.Rd, man/separate.Rd, man/spread.Rd, man/unite.Rd, tests/testthat/_snaps/chop.md, tests/testthat/_snaps/drop-na.md, tests/testthat/_snaps/expand.md, tests/testthat/_snaps/extract.md, tests/testthat/_snaps/gather.md, tests/testthat/_snaps/nest-legacy.md, tests/testthat/_snaps/nest.md, tests/testthat/_snaps/pack.md, tests/testthat/_snaps/pivot-long.md, tests/testthat/_snaps/pivot-wide.md, tests/testthat/_snaps/pivot.md, tests/testthat/_snaps/rectangle.md, tests/testthat/_snaps/replace_na.md, tests/testthat/_snaps/separate.md, tests/testthat/_snaps/spread.md, tests/testthat/_snaps/uncount.md
- Require rlang >= 1.0.0
- Update documentation with new rlang aliases
- Update snapshot tests with new rlang error style (not passing through error calls yet)
=> Update to rlang 1.0.0

DESCRIPTION, NEWS.md, R/pivot-wide.R, man/pivot_wider.Rd, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R
Closes #1318 
This PR improves on the `id_cols` error message that occurs when a column selected by `id_cols` was also selected by `names_from` or `values_from` (which meant that it was already removed at this point, resulting in the OOB error).
``` r
library(tidyr)
df <- tibble(name = c("x", "y"), value = c(1, 2))
pivot_wider(df, id_cols = name, names_from = name, values_from = value)
#> Error in `stop_subscript()`:
#> ! Can't subset columns that don't exist.
#> x Column `name` doesn't exist.
#> Error in `select_wider_id_cols()`:
#> ! `id_cols` can't select a column already selected by `names_from` or `values_from`.
#> x Column `name` has already been selected.
```
@lionel- does this usage of `try_fetch()` look right to you? In particular, I have used both `abort(parent = NA)` and …
=> Improve `id_cols` OOB error message

NEWS.md
#1332 
I understand you won't realistically bump the version after-the-fact, but I think it's a good idea to modify the NEWS file. Previously [there was no mention of the inability to complete on a grouping](https://github.com/tidyverse/tidyr/blob/49753836537547511e331b1d55a44b3471b8f422/R/complete.R) so it's very possible others have done it and usually when code breaks you search for breaking changes to try to debug.
=> NEWS: mention breaking change related to #1332

R/utils.R
Now that `vec_init()` is faster (r-lib/vctrs#1423).
=> Use `vec_init()` instead of `vec_slice()`

DESCRIPTION, man/tidyr-package.Rd
Mainly to recognize the contribution via https://github.com/tidyverse/tidyr/blob/main/src/melt.cpp (originally pulled from https://github.com/hadley/reshape/blob/master/src/melt.cpp).
=> add kevin as contributor

DESCRIPTION, man/deprecated-se.Rd, man/nest.Rd, man/nest_legacy.Rd, man/pivot_longer_spec.Rd, man/pivot_wider_spec.Rd, man/tidyr-package.Rd
- Fixed an incorrectly linked `drop` argument in the `spread_()` docs (it previously linked to the deprecated `.drop` of `unnest()`)
- Greatly improved the `pivot_longer_spec()` and `pivot_wider_spec()` docs through directly inheriting pairs of arguments like `names_sep, names_pattern`
=> Update roxygen2 to 7.2.0

DESCRIPTION, tests/testthat/_snaps/pivot-long.md, tests/testthat/_snaps/pivot-wide.md
rlang 1.0.3 fixed the `arg_match0()` call bug
=> Bump rlang version and update snapshots

vignettes/tidy-data.Rmd
In the vignette tidy-data.Rmd, when you read the example data from classroom2.csv:
```R
read.csv("classroom2.csv", stringsAsFactors = FALSE)
```
Suzy's grade on quiz1 should be `"F"` but it's read as `FALSE`. That's because of `read.csv()` defaults. This fix is needed for consistency with the previous example:
```R
classroom <- read.csv("classroom.csv", stringsAsFactors = FALSE)
```
=> Make import of data from classroom.csv and classroom2.csv consistent in tidy-data.Rmd vignette

NEWS.md, R/pivot-long.R, R/pivot-wide.R, man/pivot_longer.Rd, man/pivot_longer_spec.Rd, man/pivot_wider.Rd, man/pivot_wider_spec.Rd, revdep/README.md, revdep/cran.md, revdep/failures.md, revdep/problems.md, tests/testthat/_snaps/pivot-long.md, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-long.R, tests/testthat/test-pivot-wide.R
Closes #1350 
- `pivot_longer()` and `pivot_wider()` dots have been moved to the front, after the required args but before any optional ones. `check_dots_used()` ensures that typos are caught.
- `pivot_longer_spec()`, `pivot_wider_spec()`, `build_longer_spec()`, and `build_wider_spec()` have all gained dots that are also placed up front. `check_dots_empty()` ensures that typos are caught.
This should make it much easier to extend these functions going forward. I see two big benefits:
- For developers: it should mean we can add arguments to the generic after the `...` and not automatically break any packages that have added S3 methods for these functions
- For users: it forces them to specify arguments by name, creating more robust and readable code. We will be able to add new arguments in …
=> Adjust dots in pivoting functions

DESCRIPTION, R/complete.R, R/expand.R, R/unnest-wider.R, R/utils.R, tests/testthat/_snaps/unnest-helper.md, tests/testthat/_snaps/unnest-wider.md, tests/testthat/test-hoist.R
Closes https://github.com/tidyverse/tidyr/issues/1422
Updated and activated a test related to https://github.com/tidyverse/tidyr/issues/1203 now that `pluck()` retains empty elements correctly.
Updated snapshots, but these seem to be a little backwards. Really `unnest_wider()` calls `map()`, but the `.f` we call `map()` with accepts an `error_call` argument and that `error_call` points to `unnest_wider()` as the function to use in the errors. So it ends up looking like `map()` calls `unnest_wider()`.
=> Updates for purrr/stringr/dplyr

NEWS.md, R/utils.R
Closes https://github.com/tidyverse/tidyr/issues/1426
I think the only reason to use `glue()` was the handling in the case of empty input. This is already covered in tests (`names_sep` works with empty elements (#1185)`).
``` r
library(tidyr)
df <- tibble(
id = 1:10e3,
x = list(1:3)
)
bench::mark(
unnest_wider = unnest_wider(df, x, names_sep = "_")
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 × 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 unnest_wider    1.79s    1.79s     0.558    3.66MB     22.3
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 × 6
#>   expression        min   median …
```
=> Speed up `pivot_wider(names_sep = ...)`

NEWS.md, R/pivot-long.R, R/pivot-wide.R, README.Rmd, README.md, man/check_pivot_spec.Rd, man/pivot_longer_spec.Rd, man/pivot_wider.Rd, man/pivot_wider_spec.Rd, vignettes/pivot.Rmd, vignettes/tidy-data.Rmd
Just caught this while reading the docs. Thank you!
=> Fix `pivotting` -> `pivoting` + misc typos

NEWS.md, R/pivot-long.R, man/pivot_longer.Rd, man/pivot_longer_spec.Rd, revdep/README.md, revdep/cran.md, revdep/failures.md, revdep/problems.md, tests/testthat/test-pivot-long.R
Closes #1296 
Reverts https://github.com/tidyverse/tidyr/pull/1297
Since those 4 revdeps that relied on this have been updated on CRAN for some time now.
Using `names_ptypes = list()` really isn't particularly useful, but it is at least slightly more consistent and removes a special case in the code.
`"170484b6-4f5d-46fd-9787-1ab5f83861d1"` - 6 total broken revdeps but none of them look related to this so i think we can continue. Most look related to new usage of `allow_rename = FALSE` in `eval_select()`
=> Remove backwards compatible support for treating `list()` as `NULL`

R/unnest-helper.R
I stumbled over the pattern `any(map_lgl(...))` and thought there must be something better. And with `every()`, `some()` and `none()` there is something nicer in `purrr`. Also this is a bit more efficient in some cases.
=> Replace `any(map_lgl(...))`

NEWS.md, R/pivot-long.R, R/pivot-wide.R, man/pivot_longer_spec.Rd, man/pivot_wider_spec.Rd, tests/testthat/_snaps/pivot-long.md, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R
Closes #1408
Much nicer error call reporting!
Defaulted `error_call` to `current_env()` since it is reasonable to call these functions at the top level for advanced users.
=> Add `error_call` to `build_*_spec()` and `pivot_*_spec()`

NEWS.md, R/complete.R, R/expand.R, R/fill.R, man/complete.Rd, man/expand.Rd, man/fill.Rd
Closes #952
There are 4 functions that support grouped data frames in a special way (beyond just reconstruction on the way out)
- `nest()` (method)
- `expand()` (method)
- `complete()` (method)
- `fill()` (`mutate_at()`)
`nest()`, `expand()`, and `complete()` all already documented their grouped df support, having both examples and a section specifically about grouped data frames.
I've standardized all of the functions to have a `Grouped data frames:` section, repurposing existing bits as appropriate (`nest()` already had one and has no changes)
=> Document grouped data frame support

NEWS.md, R/pack.R, tests/testthat/_snaps/pack.md, tests/testthat/_snaps/separate-wider.md, tests/testthat/_snaps/unnest-wider.md, tests/testthat/_snaps/unnest.md, tests/testthat/test-pack.R, tests/testthat/test-separate-wider.R, tests/testthat/test-unnest-wider.R, tests/testthat/test-unnest.R
Closes #1425 (Unless we decide otherwise)
Related to #1367
I'd say that this resolves #1425 by giving a much better error message.
It also resolves this comment https://github.com/tidyverse/tidyr/issues/1367#issuecomment-1147998930, again with a much better error message.
It does _not_ resolve the original issue presented in #1367 about using some automatic separator for unnamed elements. I think that is related but can be thought about separately. I've kept that one open.
In general this improves errors for `unpack()`, `unnest()`, `unnest_wider()`, and the `separate_wider_*()` family.
---
There are two types of name duplication issues that can occur when unpacking, which I have called:
- inner / inner duplication (unpacking multiple columns that have duplicate inner names)
- outer / …
=> Improve on `unpack()` column name duplication errors

R/append.R, tests/testthat/test-append.R, tests/testthat/test-unite.R
This seems reasonable because `reconstruct_tibble()` has no way to restore these, and the number of rows will never change here. `dplyr:::dplyr_col_modify()` does a similar thing. The hlaR package actually relies on this, as they expect row names to persist on a data.frame after a call to `unite()`.
=> Retain row names of data.frames in `df_append()`

NEWS.md, R/chop.R, R/nest.R, R/pack.R, R/separate-longer.R, R/separate-rows.R, R/separate-wider.R, R/unnest-longer.R, R/unnest-wider.R, R/unnest.R, man/chop.Rd, man/pack.Rd, revdep/README.md, revdep/cran.md, revdep/failures.md, revdep/problems.md, tests/testthat/_snaps/chop.md, tests/testthat/_snaps/nest.md, tests/testthat/_snaps/pack.md, tests/testthat/_snaps/separate-wider.md, tests/testthat/_snaps/unnest-longer.md, tests/testthat/_snaps/unnest-wider.md, tests/testthat/_snaps/unnest.md, tests/testthat/test-chop.R, tests/testthat/test-nest.R, tests/testthat/test-pack.R, tests/testthat/test-unnest.R
Closes #1447 
Closes #1446 
- Added `error_call` to the "backend" functions of `pack()`, `unpack()`, `chop()`, and `unchop()`
- Added empty `...` to `unpack()`, `unchop()`, and `chop()`
- Disallowed renaming in all 6 of: `nest()`, `unnest()`, `pack()`, `unpack()`, `chop()`, and `unchop()`
`"8c16af6a-b91e-47df-9707-5270b389ec14"`
One change in revdeps from tidypaleo which was accidentally passing a named tidyselection through to `unnest()`. I'm happy to fix that one to get all 6 of these functions working consistently.
=> Add `error_call` and `...` to packing/chopping utilities

NEWS.md, R/nest.R, man/nest.Rd, man/unnest.Rd, revdep/README.md, revdep/cran.md, revdep/failures.md, revdep/problems.md, tests/testthat/_snaps/nest.md, tests/testthat/test-nest.R
Closes #1458 
``` r
df <- tibble(x = c(1, 1, 1, 2, 2, 3), y = 1:6, z = 6:1)
nest(df, .by = x)
#> # A tibble: 3 × 2
#>       x data            
#>   <dbl> <list>          
#> 1     1 <tibble [3 × 2]>
#> 2     2 <tibble [2 × 2]>
#> 3     3 <tibble [1 × 2]>
```
Also has these two cool new features:
``` r
nest(df, data = y, .by = x)
#> # A tibble: 3 × 2
#>       x data            
#>   <dbl> <list>          
#> 1     1 <tibble [3 × 1]>
#> 2     2 <tibble [2 × 1]>
#> 3     3 <tibble [1 × 1]>
nest(df, data = everything(), .by = x)
#> # A tibble: 3 × 2
#>       x data            
#>   <dbl> <list>          
#> 1     1 <tibble [3 × 3]>
#> 2     2 <tibble [2 × 3]>
#> 3     3 <tibble [1 × 3]>
```
This also revives the `.key` argument, with a default of `NULL`. This is a bit tricky because it used …
=> Implement `nest(.by = )` and revive `.key`

NEWS.md, R/unnest-wider.R, man/unnest_wider.Rd, tests/testthat/_snaps/unnest-wider.md, tests/testthat/test-unnest-wider.R
Closes https://github.com/tidyverse/tidyr/issues/1367
So now we get:
``` r
library(tidyr)
df <- tribble(
~x, ~y,
1, c(11, 12, 13),
2, 21
)
df |> unnest_wider(y)
#> Error in `unnest_wider()`:
#> ! Can't unnest elements with missing names.
#> ℹ Supply `names_sep` to generate automatic names.
```
Also fixes an issue where partially unnamed elements weren't being patched with automatic names. Instead they were getting name-repaired by vctrs, which ended up generating a strange (and not useful) combination of names.
``` r
library(tidyr)
df <- tribble(
~x, ~y,
1, c(11, b = 12, 13),
2, 21
)
df |> unnest_wider(y, names_sep = "_")
#> New names:
#> • `` -> `...1`
#> • `` -> `...3`
#> # A tibble: 2 × 5
#>       x y_...1   y_b y_...3   y_1
#>   <dbl>  <dbl> <dbl>  <dbl> <dbl>
#> 1     1     11    12 …
```
=> Error on unnamed values if `names_sep` isn't provided

DESCRIPTION, R/extract.R, R/nest.R, R/pack.R, R/pivot-long.R, R/separate-longer.R, R/separate-wider.R, R/separate.R, R/unnest-wider.R, R/utils.R, tests/testthat/_snaps/nest.md, tests/testthat/_snaps/pack.md, tests/testthat/_snaps/unnest-helper.md, tests/testthat/_snaps/unnest-wider.md
Closes #1440
- Required purrr 1.0.1
- Switched from `lapply()` to `map()` everywhere
- Added `with_indexed_errors()` to ease rethrowing with a custom message
@hadley, @lionel- what do you think of this rethrowing pattern in `with_indexed_errors()`? It seems useful to expose `message` so the caller of `with_indexed_errors()` can customize as needed, and I've fiddled with the environment so that cli interpolation works as usual AND you get access to `cnd` when the `message` is eventually interpolated.
=> Rethrow purrr index errors

R/expand.R, man/complete.Rd, man/deprecated-se.Rd, man/expand.Rd
Closes #1456
Since one is _always_ inherited from the other, and you typically learn about both around the same time, it feels fine to mention both here since it makes the `complete()` docs easier to understand
=> Tweak `expand()` dots documentation to mention `complete()`

DESCRIPTION, NEWS.md, R/expand.R
We can wait to merge until after vctrs is on CRAN.
`vec_expand_grid()` doesn't splice unnamed data frames. It requires all inputs to be named. So this requires a little tweaking to account for that. 
I really don't know if splicing unnamed data frames is a particularly useful feature, so I tried to be more conservative in `vec_expand_grid()` and didn't allow that for now. I think it makes the `vec_expand_grid()` implementation simpler since this is a feature I don't feel particularly strongly about.
=> Use `vec_expand_grid()`

README.Rmd, README.md
The `README` (`README.md` and `README.Rmd`) files have a typo in the definition of tidy data. I changed the text from "Every column is variable" to "Every column is a variable".
It's a very minor change but important because these sentences have different meanings. Without the "a", it is more difficult to understand what tidy data is, and this is the first thing you see when you go to `tidyr`'s homepage.
=> Fix typo in definition of tidy data in README

R/separate-wider.R, tests/testthat/_snaps/separate-wider.md
Fixes tidyverse#1475. The `separate_wider_position()` and `separate_wider_regex()` functions provide the `too_few` argument to control their behavior when one or more of the strings cannot be separated into as many pieces as the user specifies. When this happens, the error message that is displayed recommends specifying too_few as "start", rather than the valid value "align_start".
This pull request changes the error messages to recommend using "align_start" instead of "start".
=> Fix `separate_wider_*()` error messages

NEWS.md
Hi! The new `separate_wider_regex` functions seems to be inspired by previous work in my namedCapture/nc packages, so I would suggest making it clear about where that idea comes from. At least in the academic/university, attribution is important so it would be useful for people to know/cite my related R Journal papers, 
https://journal.r-project.org/archive/2019/RJ-2019-050/index.html
https://journal.r-project.org/archive/2021/RJ-2021-029/index.html
=> give attribution to previous work in nc package

README.Rmd, README.md
The README currently recommends using the `separate()` and `extract()` functions to transform a single character column into multiple character columns. `separate()` has been superseded by `separate_wider_delim()` and `separate_wider_position()`, and `extract()` has been superseded by `separate_wider_regex()`. This commit updates the README to reflect this.
=> In README, replace `separate()` and `extract()` with superseding functions

README.Rmd, README.md, vignettes/tidy-data.Rmd
This commit updates the definition of tidy data used in the README and the vignette to match the one presented in ["R for Data Science (2e)"](https://r4ds.hadley.nz/data-tidy#sec-tidy-data).
=> Standardize definition of tidy data

NEWS.md, R/pivot-wide.R, tests/testthat/_snaps/pivot-wide.md
Closes #1516 
Uses `.by` syntax in helper message
=> Use .by syntax in pivot_wider dplyr helper message

DESCRIPTION, NEWS.md, R/complete.R, R/expand.R
=> require dplyr 1.1.0

DESCRIPTION, NEWS.md, R/pivot-wide.R, tests/testthat/_snaps/pivot-wide.md, tests/testthat/test-pivot-wide.R
=> improve error message for non data.frame inputs

R/pivot-long.R, man/pivot_longer.Rd, man/pivot_longer_spec.Rd
In the documentation for `values_drop_na`, there is a reference to a `value_to` column, it should be `values_to`.
=> value_to -> values_to in `values_drop_na` docs

NEWS.md, R/unite.R, tests/testthat/test-unite.R
=> unite works for empty selections

NEWS.md, R/expand.R, man/expand.Rd, man/expand_grid.Rd, tests/testthat/_snaps/expand.md, tests/testthat/test-expand.R
=> Add .vary parameter to expand_grid()

NEWS.md, R/chop.R, tests/testthat/_snaps/chop.md, tests/testthat/_snaps/unnest.md, tests/testthat/test-chop.R
=> Improve `unchop()` error for incompatible ptype

NEWS.md, R/fill.R, man/fill.Rd, tests/testthat/_snaps/fill.md, tests/testthat/test-fill.R
=> Add `.by` to `fill()`
